# Generated by Django 4.2.7 on 2023-11-09 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250)),
                ('movie_poster', models.FileField(upload_to='movie/')),
                ('movie_description', models.TextField()),
                ('releasing_date', models.DateField()),
                ('director', models.CharField(max_length=250)),
                ('runtime', models.CharField(max_length=100)),
                ('genre', models.TextField()),
                ('cast', models.TextField()),
                ('trailer_iframe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NowShowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.TimeField()),
                ('running_date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.movie')),
            ],
        ),
    ]
