# Generated by Django 4.2.7 on 2023-11-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='nowshowing',
            name='show_time',
        ),
        migrations.AddField(
            model_name='nowshowing',
            name='show_time',
            field=models.ManyToManyField(to='admin_page.showtime'),
        ),
    ]
