# Generated by Django 4.2.7 on 2024-01-23 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_page', '0003_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='show_time',
        ),
        migrations.AddField(
            model_name='booked',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.showtime'),
        ),
        migrations.AlterField(
            model_name='booked',
            name='seat',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='booked',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_page.nowshowing'),
        ),
        migrations.AlterField(
            model_name='booked',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
